<?php $this->placeholder('css')->captureStart(); ?>
body{margin:0; padding:0;}
#container{padding:1%;display:block;max-width:600px;width:60%;overflow:hidden;margin:0 auto;}
#board{padding:1%;display:block;max-width:600px;width:60%;overflow-x:hidden;margin:0 auto;max-height:400px;overflow-y:auto;}
<?php $this->placeholder('css')->captureEnd(); ?>
<script type="text/javascript">
<?php $this->headScript()->captureStart()?>
	var Server;
	function log( text ) {
		$log = $('#board');
		//Add text to log
		var tempText = $("<div></div>");
		tempText.text(text);
		text = tempText.html();
		$log.append(($log.html()?"<br />":'')+text);
		//Autoscroll
		$log[0].scrollTop = $log[0].scrollHeight - $log[0].clientHeight;
	}

	function send( text ) {
		Server.send( text );
	}

	$(document).ready(function() {
		log('Connecting...');
		Server = new ZS('ws://192.168.3.253:9000');
		

		$('#message').keypress(function(e) {
			if ( e.keyCode == 13 && this.value ) {
				log( 'You: ' + this.value );
				message = '{"message":"tirth","action":"index","controller":"index","module":"default"}';
				send( message );
				$(this).val('');
			}
		});

		//Let the user know we're connected
		Server.bind('open', function() {
			log( "Connected. welcome to heavan!!!" );
		});

		//OH NOES! Disconnection occurred.
		Server.bind('close', function( data ) {
			log( "Disconnected." );
		});

		//Log any messages sent from server
		Server.bind('message', function( payload ) {
			json = $.parseJSON(payload);
			console.log(payload);
			$("#output").html(json.message);
		});

		Server.connect();
	});
	// Temporary data
<?php $this->headScript()->captureEnd(); ?>
</script>
<div>
	<div id="board"></div>
	<?php echo $this->form;?>
	<!-- <textarea id='log' name='log' readonly='readonly'></textarea> -->
	<!-- <br /> <input type='text' id='message' name='message' /> -->
</div>
<div id="output"></div>